services:
  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
      - "8445:8445"
    volumes:
      # Mount custom nginx.conf from local directory
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount certificates from local directory
      - ./certs:/etc/nginx/certs:ro
      # Optionally, mount a directory for site-specific configs
      # - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/var/www/html
    restart: unless-stopped